Updating this neuron a bit
kalliope-project/kalliope_neuron_tasker pull request #2
Opened 2018-08-19 17:39 UTC by daylicron

Hey,
I noticed the following two things, when I started to use this neuron:
- install.yml: Version bum of requests as kalliope requires =>13.x
- tasker_autoremote.py: Add option for password if someone wants to secure autoremote in addition with a password

Cheers
Dennis

2018-08-19 18:24 UTC, Sispheor commented
You can remove the "version line for the install. It will take the last version available.

2018-08-19 18:25 UTC, Sispheor requested changes

2018-08-19 18:25 UTC, Sispheor commented on tasker_autoremote.py
> +                    'password': self.password}
If you set it in the payload, then it become mandatory and will be set to None for those who havn't set it in the neuron. And I presume that the API will fail if the received password key is empty.

2018-08-19 19:46 UTC, daylicron commented on tasker_autoremote.py
> +                    'password': self.password}
I checked this before and it works when you leave password empty. Maybe someone can confirm this.

2018-08-19 20:28 UTC, Sispheor commented on tasker_autoremote.py
> +                    'password': self.password}
It's anyway better to only add it when provided. Use the update method on the data dict.

2018-08-19 20:29 UTC, Sispheor commented
Missing doc update also.

2018-08-23 19:46 UTC, daylicron commented
@Sispheor : sry, I've been quite busy. I've built in your recommendations. Anything else missing here?

2018-08-23 21:00 UTC, Sispheor approved these changes

2018-08-23 21:01 UTC, merged